### ISSUE TITLE
Not seeing "test passed" information in report

### ISSUE THREAD

**Issue by joelransom** [picklesdoc/pickles#365]
Hi. I am having an issue where the "pass" checkmark is not appearing in the report. I don't know how to troubleshoot because I don't know how you get that in the first place. Could you please help me understand how you identify test pass/fail status in the test result xml file? I've attached an actual TestResult.xml file that doesn't seem to be working. 

I hope this is the appropriate place to ask this. 

Thanks

Joel

[TestResult.zip](https://github.com/picklesdoc/pickles/files/446012/TestResult.zip)

**Comment by dirkrombauts** [comment]
Hi,

Yes, this is a good place to ask your question.

Could you please give some more information about how you use Pickles? Are you using the command line version, the GUI version, the powershell version or the MSBuild version? Which arguments are you supplying?

**Comment by joelransom** [comment]
Dirk, thanks for the reply. I'm using the command line version. (I should check out the other versions.) Example follows, with actual paths replaced by <path> to shorten it. 

<path>\pickles.exe --documentation-format=dhtml --feature-directory=<path>\Tests --output-directory=.\documentation --link-results-file=<path>TestResult.xml --test-results-format=nunit3

**Comment by dirkrombauts** [comment]
Hi,
I had another look at your TestResult.xml file ... I understand now that Pickles will not show the "pass" checkmark in the report.

The TestResult.xml seems incomplete. It mentions there are 119 tests, but it's only a handful of lines. So you might want to investigate how this TestResult.xml file was created.

Pickles uses the attributes on the individual test cases to determine whether a scenario passed. A feature is marked "passed" if all scenarios pass, and the entire report is marked "passed" if all features are marked "passed". Since your TestResult.xml file does not contain the data of the individual test cases, Pickles cannot calculate any pass/fail states.

**Comment by joelransom** [comment]
Dirk - Here's the command I used to generate that file: 
`<path>NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe <path>\Tests.dll -v --where cat=Manager --result TestResult.xml;format=nunit3`
There were (I assume) 119 tests total, but only one satisfied the criteria "where cat=Manager" so only one was run, which passed:
`<test-case id="1-1020" name="AsManagerICanAssignClaimsToAuditor("Complex Manager","manager","Complex","Excellus","ExcellusReadmission","Tim Complex Auditor",System.String[])" fullname="SpecFlowTest.Tests.AssignClaimsToAuditorFeature_NUnit.AsManagerICanAssignClaimsToAuditor("Complex Manager","manager","Complex","Excellus","ExcellusReadmission","Tim Complex Auditor",System.String[])" runstate="Runnable" **result="Passed"** duration="18.955931" asserts="6"/>`

**Comment by dirkrombauts** [comment]
OK, would it be possible to attach the .feature file too? You can remove the steps from the scenarios if they are confidential: I only need the feature title and the scenario title.

**Comment by joelransom** [comment]
It looks like this, if it helps: 
`Feature: AssignClaimsToAuditor
	Description...

@Manager @Complex
Scenario Outline: As Manager I can assign claims to auditor
	Given I have logged in as <U>


Examples: 
| Scenario 	| U  	| AT | CO   | CT| AU|
| X 		| X 	| X  | X 	| X | X |`

**Comment by dirkrombauts** [comment]
Thanks, I'll try to debug this asap.

**Comment by dirkrombauts** [comment]
Right, I traced this to an entry in the TestResults.xml file: it says `<property name="_DESCRIPTION" value="AssignClaimsToAuditor" />` instead of `<property name="Description" value="AssignClaimsToAuditor" />`.

I asked a question about it on the NUnit project: https://github.com/nunit/nunit/issues/1781

I will keep you posted if I know more.

**Comment by dirkrombauts** [comment]
One more question: which version of SpecFlow do you use?

**Comment by joelransom** [comment]
2.1

**Comment by rprouse** [comment]
@joelransom are you using any other libraries other than SpecFlow in your tests?

**Comment by rprouse** [comment]
@joelransom, sorry if that is a stupid question in relation to SpecFlow, I haven't used it before, but we (the NUnit team) were asked about this and determining where the non-standard _DESCRIPTION and _CATEGORIES are coming from would help us with some issues our users have filtering tests. Like Pickles, NUnit does not recognize those properties.

**Comment by joelransom** [comment]
No question is stupid when someone is trying to be helpful. These are selenium webdriver tests for GUI automation so those libraries are included. But if  _DESCRIPTION and _CATEGORIES are not supposed to be there then that is odd because this was output from nunit console. 
Before I started using nunit console I was using specrun with is the test runner for specflow. 
Maybe I should step back and try to create an example from scratch to eliminate as many variables as possible. I'm actually not at work today for the holiday weekend so I will pursue that next week.

**Comment by dirkrombauts** [comment]
I just updated my test harness so that it uses NUnit 3.4.1 and SpecFlow 2.1 to generate the sample test output data I'm using. The result file has the expected Description and Categories strings.

So I don't know what's going on here :-(

**Comment by dirkrombauts** [comment]
@joelransom it would be really cool if you could create a small project that demonstrates the problem!

**Comment by dirkrombauts** [comment]
@joelransom a question that came up on the NUnit project: which operating system are you using?

**Comment by joelransom** [comment]
Sorry couldn't get back to this for a few days. OS is Windows 8.1 (lame). I will look into this a little further to see what's up with the "he non-standard _DESCRIPTION and _CATEGORIES" entries.

**Comment by joelransom** [comment]
So, while googling around for more info I came across https://github.com/nunit/nunit/issues/1781
and https://github.com/techtalk/SpecFlow/issues/705. I saw Charlie Poole's comments about nunit2 tests vs nunit3 tests. Although I was using the latest nunit console runner, my nunit version with 2.6. It hadn't been updated for the simple reason that I wasn't using nunit (I was using specrun) until very recently. 
I updated my nunit to the latest version and the properties are now displaying as expected. 

Thanks to all who participated in this discussion.

**Comment by dirkrombauts** [comment]
@joelransom so you problem is solved? great. Can I close the issue?

**Comment by joelransom** [comment]
Yes you can, thanks for your help.

**Comment by dirkrombauts** [comment]
For what it's worth: using NUnit 2.6.3 as runtime and NUnit 3.4.1 as test runner I get _DESCRIPTION as well. So now it's at least reproducible.

**Comment by joelransom** [comment]
I'm still not getting the 'passed' flag.  Attached is what the TestResult.xml file looks like now, along with the corresponding feature file. 

[Login.zip](https://github.com/picklesdoc/pickles/files/462829/Login.zip)
[TestResult.zip](https://github.com/picklesdoc/pickles/files/462808/TestResult.zip)

I will still try to create an sample solution for you if you are interested, but it might take a  few days.

**Comment by dirkrombauts** [comment]
Thanks for the attachments.

I will do my best to look into it early next week.

**Comment by dirkrombauts** [comment]
Hi,
I tried out your test result file and your login.feature file, and I see the passed checkmark next to the login feature in the table of content, and next to the "login" and "login as multiple users" scenarios.

FYI I did this using the GUI version of Pickles.

**Comment by dirkrombauts** [comment]
Are you still experiencing this problem? If so, could you please give me more data so I can try to reproduce it? Thanks!

**Comment by joelransom** [comment]
Dirk I have not been able to get back to it this week, sorry, I've working on something else. I do intend to try the gui runner you referenced.

**Comment by joelransom** [comment]
Dirk, I'm starting to think the issue is that it doesn't work when generating dhtml.

**Comment by dirkrombauts** [comment]
Joel, is it perhaps possible you are talking about seeing a "passed" flag next to each individual example row in the Examples table? That does indeed not work in the current version of the DHTML formatter.

**Comment by dirkrombauts** [comment]
I'm closing this issue since I haven't heard anything for two months. I'm assuming you are talking about the DHTML formatter, which does not support showing the results of individual example rows.
